name: CI

concurrency: ci

on:
    push:
        branches: [develop]
        paths:
            - "src/**/*.rs"
            - Cargo.toml
            - .rust-version
    workflow_dispatch:

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: Linux
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-musl
                    # - build: macos
                    #   os: macos-latest
                    #   target: x86_64-apple-darwin

        steps:
          - uses: actions/checkout@v4
          - name: Get language version
            id: get_lang_version
            run: |
                  v=$(cat .rust-version)
                  echo "lang_version=$v" >> $GITHUB_OUTPUT
          - name: Install Rust
            # Or @nightly if you want
            uses: dtolnay/rust-toolchain@stable
            # Arguments to pass in
            with:
              # Make Rust compile to our target (defined in the matrix)
              targets: ${{ matrix.target }}
              # rust-version: ${{ steps.get_lang_version.outputs.lang_version }}
          - name: Build
            uses: actions-rs/cargo@v1
            with:
              use-cross: true
              command: test
              args: --verbose --release --target ${{ matrix.target }}
          - name: publish-docs
            uses: peaceiris/actions-gh-pages@v4
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./coverage

    #    docs:
    #        needs: [tests]
    #        runs-on: ubuntu-latest
    #        concurrency: docs
    #        steps:
    #            - uses: actions/checkout@v4
    #            - uses: actions/setup-python@v5
    #              with:
    #                  python-version: "3.11"
    #            - name: install-deps
    #              run: pip install -r requirements/docs.txt
    #            - name: make-docs
    #              run: cd docs && make html
    #            - name: publish-docs
    #              uses: peaceiris/actions-gh-pages@v4
    #              with:
    #                  github_token: ${{ secrets.GITHUB_TOKEN }}
    #                  publish_dir: ./docs/_build/html

    release:
        needs: [tests]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
            - name: Bump version and push tag
              id: bump_version
              uses: anothrNick/github-tag-action@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                WITH_V: false
                DEFAULT_BUMP: patch
            - name: Update Cargo.toml
              run: |
                    sed -i 's/^version = ".*"$/version = "'${{ steps.bump_version.outputs.new_tag }}'"/' Cargo.toml
            - name: Commit and push
              run: |
                    git config --global user.email "ci@pilgrimagesoftware.com"
                    git config --global user.name "Pilgrimage Software CI"
                    git add Cargo.toml
                    git commit -m "Update Cargo.toml on ${{ github.ref_name }} with version: ${{ steps.bump_version.outputs.new_tag }}"
                    git push origin --tags
            - name: Run release-plz
              uses: release-plz/action@v0.5
              with:
                  command: release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_KEY }}
